spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2/tenant_admin
    username: username
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/migrate/v1.0.0/sql-init.sql
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml