spring:
  application:
    name: sass-admin
  profiles:
    include:
      - postgresql
base:
  framework:
    cache:
      service:
        cache-service-type: caffeine
    kms:
      default:
        sm2:
          auto-generate: true
