name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'
      - name: "Cache Maven Repos"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Checkout Parent Dependency
        run: |
          git clone -b develop https://github.com/fuhouyu/base-framework.git
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      # 安装父级依赖
      - name: Install dependencies
        run: mvn clean install -DskipTests -f base-framework/pom.xml

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2092355812 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'